edition = "2021"
max_width = 140
indent_style = "Block"
reorder_imports = true
reorder_modules = true
condense_wildcard_suffixes = true
normalize_comments = true
use_try_shorthand = true
reorder_impl_items = true
imports_layout = "HorizontalVertical"
imports_granularity = "Crate"
