name: Build & Test

on:
  push:
    branches:
      - '**'

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: full
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-apple-darwin]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update local toolchain
      run: |
          rustup set profile minimal
          rustup toolchain install stable
          rustup default stable
          rustup override set stable
          rustup target add --toolchain stable ${{ matrix.target }}

    - name: Toolchain info
      run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version

    - name: Test
      run: |
          cargo check
          cargo clippy -- -D warnings
          cargo test --all --target ${{ matrix.target }}