name: Build & Publish Docker Image

on:
  push:
    tags:
      - v*

env:
  DOCKER_IMAGE: ghcr.io/${{ github.repository_owner }}/lurk

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE }}

      - name: Build and publish Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/386,linux/amd64,linux/arm64/v8
          tags: ${{ steps.metadata.outputs.tags }}
          push: true